// Repositorio Iberoamericano de Capacitaciones Forenses 2026
// Fuente: repositorio_capacitaciones_forenses_iberoamerica_2026.xlsx
// 52 registros verificados · Última actualización: 16/06/2026

const MCF_CAPACITACIONES = [
  {
    "id": "FOR-001",
    "nombre": "Jornadas de Actualización Forense 2026",
    "area": "Ciencia y Estándares Periciales",
    "institucion": "Poder Judicial de Neuquén (CMF)",
    "tipo": "Pública",
    "modalidad": "Presencial",
    "duracion": "2 Días",
    "precio": "Gratuito",
    "moneda": "ARS",
    "fecha": "2026-10-01",
    "url": "https://www.jusneuquen.gov.ar/jornadas-cmf-2026/",
    "contacto": "CMF Neuquén",
    "pais": "Argentina"
  },
  {
    "id": "FOR-002",
    "nombre": "Introducción a la Psicopatología Forense",
    "area": "Psicopatología y Práctica Pericial",
    "institucion": "Academia de Ciencias Forenses (ACFRA)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "6 Encuentros",
    "precio": "40000",
    "moneda": "ARS",
    "fecha": "2026-07-15",
    "url": "https://www.acfra.org.ar/",
    "contacto": "info@acfra.org.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-056",
    "nombre": "Curso: Evaluaciones Forenses en la Justicia de Familia 2026",
    "area": "Psicología / Psiquiatría / Derecho de Familia",
    "institucion": "Academia de Ciencias Forenses (ACFRA)",
    "tipo": "Privada",
    "modalidad": "Sincrónica / Asincrónica",
    "duracion": "13 abr. al 13 jul. · lunes 18 a 20 hs",
    "precio": "210000 (1 pago) / 260000 (6 cuotas)",
    "moneda": "ARS",
    "fecha": "2026-04-13",
    "url": "https://www.acfra.org.ar/cursos/cursos-2026/evaluaciones-familia/",
    "contacto": "ACFRA",
    "pais": "Argentina"
  },
  {
    "id": "FOR-057",
    "nombre": "Curso: Aspectos Forenses del Trastorno del Espectro Autista (TEA)",
    "area": "Psicología / Psiquiatría Forense",
    "institucion": "Academia de Ciencias Forenses (ACFRA)",
    "tipo": "Privada",
    "modalidad": "Sincrónica / Asincrónica",
    "duracion": "4 ago. al 20 oct. · lunes 18 a 20 hs",
    "precio": "210000 (1 pago) / 260000 (3 cuotas)",
    "moneda": "ARS",
    "fecha": "2026-08-04",
    "url": "https://www.acfra.org.ar/cursos/cursos-2026/forense-tea/",
    "contacto": "ACFRA",
    "pais": "Argentina"
  },
  {
    "id": "FOR-058",
    "nombre": "Workshop: Psicología Forense Aplicada",
    "area": "Psicología Forense / Peritaje",
    "institucion": "Academia de Ciencias Forenses (ACFRA)",
    "tipo": "Privada",
    "modalidad": "Sincrónica",
    "duracion": "4 encuentros · 09/04, 11/06, 13/08, 08/10 · jueves 18 a 22 hs",
    "precio": "176000 (1 pago) / 208000 (3 cuotas)",
    "moneda": "ARS",
    "fecha": "2026-04-09",
    "url": "https://www.acfra.org.ar/workshops/workshops-2026/psicologia-forense-aplicada-1/",
    "contacto": "ACFRA",
    "pais": "Argentina"
  },
  {
    "id": "FOR-062",
    "nombre": "Diplomatura Internacional de Drones en la Búsqueda y Rescate de Personas",
    "area": "Búsqueda y Rescate / Investigación de Personas Desaparecidas",
    "institucion": "Círculo Argentino de Seguridad (CAS)",
    "tipo": "ONG",
    "modalidad": "Virtual (Zoom) — 20 hs. sincrónicas + 70 hs. asincrónicas",
    "duracion": "20 jul. al 14 dic. · lunes 20 a 22 hs",
    "precio": "225000 (contado) / 5 cuotas de 50000 (socios) — no socios: 250000 / 5 cuotas de 60000",
    "moneda": "ARS",
    "fecha": "2026-07-20",
    "url": "https://circuloargentinodeseguridad.com/diplomatura-internacional-de-dron-de-busqueda-y-rescate-de-personas",
    "contacto": "circuloargentinodeseguridad@gmail.com",
    "pais": "Argentina"
  },
  {
    "id": "FOR-063",
    "nombre": "Club Forense — Catálogo de Cursos y Webinars On-Demand",
    "area": "Criminalística / Tanatopraxia / Psicología Jurídica / Balística / Multidisciplinaria",
    "institucion": "Centro de Especialización Forense (CEF Virtual)",
    "tipo": "Privada",
    "modalidad": "Virtual / Asincrónica",
    "duracion": "Inscripción permanente · +30 cursos y webinars 100% online",
    "precio": "Desde 25000 (webinar) — membresía mensual disponible",
    "moneda": "ARS",
    "fecha": "2026-01-01",
    "url": "https://institutocef.com.ar/",
    "contacto": "cefvirtual (Instagram) / info@inscripcionescursoscef.com.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-064",
    "nombre": "III Jornada Interdisciplinaria Forense 2026 (#JIF2026)",
    "area": "Ciencias Forenses / Interdisciplinaria",
    "institucion": "Centro Interdisciplinario de Investigaciones Forenses (CIDIF) — Academia Nacional de Ciencias de Buenos Aires (ANCBA)",
    "tipo": "Pública",
    "modalidad": "Presencial + Zoom",
    "duracion": "13 y 14 de agosto · 14 a 19:30 hs",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-08-13",
    "url": "https://www.eventbrite.com/e/iii-jornada-interdisciplinaria-forense-2026-jif2026-cidif-ancba-tickets-1984498132335",
    "contacto": "CIDIF - ANCBA",
    "pais": "Argentina"
  },
  {
    "id": "FOR-059",
    "nombre": "Curso de posgrado: Tanatología Forense",
    "area": "Tanatología / Medicina Legal",
    "institucion": "Asociación de Médicos Forenses de la Rep. Argentina (AMFRA) · Fac. Medicina UBA",
    "tipo": "Pública/Privada",
    "modalidad": "Presencial",
    "duracion": "Posgrado",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-09-01",
    "url": "https://amfra.org.ar/curso-de-posgrado-tanatologia-forense/",
    "contacto": "amfraforenses@gmail.com",
    "pais": "Argentina"
  },
  {
    "id": "FOR-003",
    "nombre": "Escuela Latinoamericana de Cs. Forenses y DDHH 2026 (EAAF)",
    "area": "Antropología Forense / DDHH",
    "institucion": "Equipo Argentino de Antropología Forense (EAAF)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "Intensivo 92 hs",
    "precio": "Gratuito",
    "moneda": "ARS",
    "fecha": "2026-06-01",
    "url": "https://eaaf.org/escuela-latinoamericana-de-ciencias-forenses-2026/",
    "contacto": "capacitaciones@eaaf.org",
    "pais": "Argentina"
  },
  {
    "id": "FOR-004",
    "nombre": "Diplomatura en Pericias Forenses y Evisceración",
    "area": "Morfología / Práctica de Morgue",
    "institucion": "ISE Cursos — Educación a Distancia",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Flexible",
    "precio": "Gratuito",
    "moneda": "ARS",
    "fecha": "2026-01-01",
    "url": "https://www.isecursos.com/detalle-3434",
    "contacto": "atencion@isecursos.com",
    "pais": "Argentina"
  },
  {
    "id": "FOR-006",
    "nombre": "Curso de Práctica Procesal Pericial",
    "area": "Práctica Pericial y Procesal",
    "institucion": "Colegio de Abogados de La Plata (CALP)",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "12 Clases",
    "precio": "65000",
    "moneda": "ARS",
    "fecha": "2026-07-05",
    "url": "https://caubauno.org/2026/03/20/curso-de-capacitacion-en-practica-procesal-peritos-2026/",
    "contacto": "cursos@caubauno.org",
    "pais": "Argentina"
  },
  {
    "id": "FOR-009",
    "nombre": "Curso de Evidencias Biológicas en la Investigación Criminal",
    "area": "Biología y ADN Forense",
    "institucion": "Universidad Nacional de La Plata (UNLP)",
    "tipo": "Pública",
    "modalidad": "Híbrido",
    "duracion": "60 horas",
    "precio": "185000",
    "moneda": "ARS",
    "fecha": "2026-10-05",
    "url": "https://www.jursoc.unlp.edu.ar",
    "contacto": "posgrado@jursoc.unlp.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-010",
    "nombre": "Especialización en Investigación de Homicidios",
    "area": "Criminalística de Campo",
    "institucion": "Instituto Universitario de la Policía Federal (IUPFA)",
    "tipo": "Pública",
    "modalidad": "Presencial",
    "duracion": "1 Año",
    "precio": "580000",
    "moneda": "ARS",
    "fecha": "2026-08-22",
    "url": "https://www.iupfa.edu.ar",
    "contacto": "posgrado@iupfa.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-011",
    "nombre": "XLV Congreso Internacional AMFRA — Medicina Legal y Cs. Forenses 2026",
    "area": "Medicina Legal / Congreso",
    "institucion": "Asoc. de Médicos Forenses de la Rep. Argentina (AMFRA)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "3 Días (13-15 May)",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-05-13",
    "url": "https://amfra.org.ar/congreso-amfra-2026/",
    "contacto": "amfraforenses@gmail.com",
    "pais": "Argentina"
  },
  {
    "id": "FOR-012",
    "nombre": "Diplomatura en Psicología Forense — UAI Cohorte 2026",
    "area": "Psicología Forense / Peritaje",
    "institucion": "Universidad Abierta Interamericana (UAI)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "180 hs / 18 Mód.",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-04-11",
    "url": "https://www.periciapsicologica.com/doc_TallerCursoGrupodeEstudio.asp?idarticulo=56",
    "contacto": "info@uai.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-013",
    "nombre": "Postgrado en Ciencias Forenses Aplicadas 2026",
    "area": "Patología / Tanatología / Medicina Legal",
    "institucion": "UNLP — Cs. Jurídicas y Cs. Naturales",
    "tipo": "Pública",
    "modalidad": "Híbrido",
    "duracion": "Módulos anuales",
    "precio": "Gratuito",
    "moneda": "ARS",
    "fecha": "2026-03-01",
    "url": "https://www.jursoc.unlp.edu.ar/index.php/posgrado/item/4385",
    "contacto": "posgrado@jursoc.unlp.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-014",
    "nombre": "Diplomatura en Identidad Humana — UTN",
    "area": "Dactiloscopia / Identificación",
    "institucion": "Universidad Tecnológica Nacional (UTN-FRRQ)",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "6 Meses",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-03-01",
    "url": "https://aprenderonline.frrq.utn.edu.ar/curso/diplomatura-en-identidad-humana/",
    "contacto": "aprenderonline@frrq.utn.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-015",
    "nombre": "Especialización Forense Interdisciplinaria — Caja Forense",
    "area": "Pericial Económico-Contable / Legal",
    "institucion": "Caja Forense (Córdoba)",
    "tipo": "Privada",
    "modalidad": "Híbrido",
    "duracion": "10 cuotas (2026)",
    "precio": "460000",
    "moneda": "ARS",
    "fecha": "2026-03-01",
    "url": "https://cforense.org/home/posgrados-y-diplomaturas-2025/",
    "contacto": "info@cforense.org",
    "pais": "Argentina"
  },
  {
    "id": "FOR-016",
    "nombre": "Conversatorio AMFRA — Interpretación de Pericias Forenses",
    "area": "Actualización / Práctica Pericial",
    "institucion": "Asoc. de Médicos Forenses de la Rep. Argentina (AMFRA)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "3 Sesiones",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-10-28",
    "url": "https://amfra.org.ar/noticias/",
    "contacto": "amfraforenses@gmail.com",
    "pais": "Argentina"
  },
  {
    "id": "FOR-018",
    "nombre": "Especialización en Investigación Forense de Violaciones de DDHH",
    "area": "Investigación Forense / DDHH",
    "institucion": "Universidad Externado de Colombia",
    "tipo": "Pública",
    "modalidad": "Presencial",
    "duracion": "3 Trimestres",
    "precio": "5720000",
    "moneda": "COP",
    "fecha": "2026-02-01",
    "url": "https://www.uexternado.edu.co/programa/estudios-del-patrimonio-cultural/especializacion-en-investigacion-forense-de-violaciones-de-derechos-humanos/",
    "contacto": "posgrados@uexternado.edu.co",
    "pais": "Colombia"
  },
  {
    "id": "FOR-019",
    "nombre": "Diplomado en Riesgos y Auditoría Forense",
    "area": "Auditoría Forense / Fraude",
    "institucion": "Politécnico de Suramérica — Medellín",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "120 Horas",
    "precio": "Consultar",
    "moneda": "COP",
    "fecha": "2026-04-01",
    "url": "https://www.polisura.edu.co/diplomado-virtual-gratis/curso-diplomado-auditoria-forense",
    "contacto": "info@polisura.edu.co",
    "pais": "Colombia"
  },
  {
    "id": "FOR-020",
    "nombre": "Diplomado en Grafología y Documentología Forense — ENAC",
    "area": "Grafología / Documentología",
    "institucion": "Escuela Nacional de Criminalística (ENAC)",
    "tipo": "Privada",
    "modalidad": "Híbrido",
    "duracion": "Varios turnos",
    "precio": "Consultar",
    "moneda": "COP",
    "fecha": "2026-02-01",
    "url": "https://www.enac.edu.co/",
    "contacto": "info@enac.edu.co",
    "pais": "Colombia"
  },
  {
    "id": "FOR-023",
    "nombre": "Maestría en Criminología Forense y Perfilación Criminal",
    "area": "Criminología / Perfilación",
    "institucion": "Instituto Ciencia Aplicada (ICA) — Online",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Cuatrimestral",
    "precio": "3200",
    "moneda": "MXN",
    "fecha": "2026-05-01",
    "url": "https://posgradoforense.com/perfilacioncriminal/",
    "contacto": "info@posgradoforense.com",
    "pais": "México"
  },
  {
    "id": "FOR-024",
    "nombre": "VII Congreso de Ciencias Forenses — UNAM",
    "area": "Odontología / Toxicología / Multidisciplinaria",
    "institucion": "UNAM",
    "tipo": "Pública",
    "modalidad": "Presencial",
    "duracion": "3 Días",
    "precio": "Consultar",
    "moneda": "MXN",
    "fecha": "2026-09-01",
    "url": "http://www.congresocienciaforense.unam.mx/",
    "contacto": "congresocienciaforense@unam.mx",
    "pais": "México"
  },
  {
    "id": "FOR-025",
    "nombre": "Diplomado en Psicología Jurídica y Forense — ADIPA 2026",
    "area": "Psicología Forense / Criminología",
    "institucion": "ADIPA Chile",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Semestral",
    "precio": "Consultar",
    "moneda": "CLP",
    "fecha": "2026-03-01",
    "url": "https://adipa.cl/diplomados/psicologia-juridica-y-forense-una-mirada-desde-la-criminalistica-criminologia-y-el-delito/",
    "contacto": "info@adipa.cl",
    "pais": "Chile"
  },
  {
    "id": "FOR-026",
    "nombre": "Diplomado en Peritaje Informático e Informática Forense 2026",
    "area": "Informática Forense / Ciberdelito",
    "institucion": "Forensic &amp; Cybercrime Investigation (FCI) — USACH",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Semestral",
    "precio": "Consultar",
    "moneda": "CLP",
    "fecha": "2026-03-01",
    "url": "https://diplomadociberseguridad.com/peritaje-informatico-e-informatica-forense-2/",
    "contacto": "info@fci.cl",
    "pais": "Chile"
  },
  {
    "id": "FOR-027",
    "nombre": "Máster Profesional en Criminalística Forense — INISEG / UCAM",
    "area": "Criminalística / Investigación Criminal",
    "institucion": "INISEG — Univ. Católica de Murcia (UCAM)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "1 Año (60 ECTS)",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2026-09-01",
    "url": "https://www.iniseg.es/criminologia/masteres-executives/master-profesional-en-criminalistica-forense.html",
    "contacto": "informacion@iniseg.es",
    "pais": "España"
  },
  {
    "id": "FOR-028",
    "nombre": "Curso de Perito Judicial en Balística Forense — UNED Málaga",
    "area": "Balística Forense / Peritaje",
    "institucion": "UNED Málaga (Addpol)",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "5 Meses / 12 ECTS",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2026-09-01",
    "url": "https://addpol.org/curso/curso-de-perito-judicial-experto-en-balistica-forense/",
    "contacto": "info@addpol.org",
    "pais": "España"
  },
  {
    "id": "FOR-029",
    "nombre": "Programa Avanzado en Peritaje Informático e Informática Forense — UNIR",
    "area": "Informática Forense / Ciberseguridad",
    "institucion": "Universidad Internacional de La Rioja (UNIR)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "4 Meses",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2026-03-16",
    "url": "https://www.unir.net/ingenieria/curso-perito-judicial-informatico/",
    "contacto": "info@unir.net",
    "pais": "España"
  },
  {
    "id": "FOR-030",
    "nombre": "Forense Digital — Microcredencial UNED",
    "area": "Análisis Forense Digital / Ciberseguridad",
    "institucion": "UNED — Formación Permanente",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "~3 Meses",
    "precio": "373.68",
    "moneda": "EUR",
    "fecha": "2025-10-20",
    "url": "https://formacionpermanente.uned.es/tp_actividad/actividad/forense-digital",
    "contacto": "fpermanente@uned.es",
    "pais": "España"
  },
  {
    "id": "FOR-031",
    "nombre": "XVIII Reunión Científica AEAOF — Oviedo 2026",
    "area": "Antropología / Odontología Forense",
    "institucion": "Asoc. Española de Antropología y Odontología Forense (AEAOF)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "2-3 Días",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2026-11-01",
    "url": "https://aeaof.com/",
    "contacto": "secretaria@aeaof.com",
    "pais": "España"
  },
  {
    "id": "FOR-032",
    "nombre": "VII Jornadas AIPJE — Psicología Jurídica y Forense / IA",
    "area": "Psicología Jurídica / IA Forense",
    "institucion": "AIPJE — Universidad de Oviedo",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "3 Días",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2025-09-25",
    "url": "https://www.aipje.com/vii-jornadas-aipje-oviedo-2025/",
    "contacto": "secretaria@aipje.com",
    "pais": "España"
  },
  {
    "id": "FOR-033",
    "nombre": "Programa Especializado en Psicología Jurídica Forense — UPC",
    "area": "Psicología Forense / Evaluación",
    "institucion": "Univ. Peruana de Ciencias Aplicadas (UPC)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Cuatrimestral",
    "precio": "Consultar",
    "moneda": "PEN",
    "fecha": "2026-03-01",
    "url": "https://postgrado.upc.edu.pe/landings/programas-especializados/psicologia/psicologia-forense/",
    "contacto": "posgrado@upc.edu.pe",
    "pais": "Perú"
  },
  {
    "id": "FOR-034",
    "nombre": "Especialización en Perito en Criminalística y Cs. Forenses",
    "area": "Criminalística / Peritaje",
    "institucion": "Universidad Continental (Perú)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Cuatrimestral",
    "precio": "Consultar",
    "moneda": "PEN",
    "fecha": "2026-04-01",
    "url": "https://mktposgrado.ucontinental.edu.pe/programa-especializacion-perito-criminalistica-ciencias-forenses",
    "contacto": "posgrado@ucontinental.edu.pe",
    "pais": "Perú"
  },
  {
    "id": "FOR-035",
    "nombre": "Capacitación Online SNMLCF — Medicina Legal y Cs. Forenses",
    "area": "Medicina Legal / Formación Pericial",
    "institucion": "Servicio Nac. de Medicina Legal y Cs. Forenses (Ecuador)",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "Modular / Flexible",
    "precio": "Gratuito",
    "moneda": "USD",
    "fecha": "2026-01-01",
    "url": "https://capacitacion.cienciasforenses.gob.ec/",
    "contacto": "capacitacion@cienciasforenses.gob.ec",
    "pais": "Ecuador"
  },
  {
    "id": "FOR-036",
    "nombre": "XIV Congreso Internacional AIPJ — Perú 2026",
    "area": "Psicología Jurídica / Congreso",
    "institucion": "Asoc. Iberoamericana de Psicología Jurídica (AIPJ)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "3 Días",
    "precio": "Consultar",
    "moneda": "PEN",
    "fecha": "2026-10-01",
    "url": "http://psicologiajuridica.com.ar/",
    "contacto": "info@aipj.org",
    "pais": "Perú"
  },
  {
    "id": "FOR-037",
    "nombre": "Jornadas Científicas en Genética Forense — SLAGF",
    "area": "Genética Forense / Identificación",
    "institucion": "Sociedad Latinoamericana de Genética Forense (SLAGF)",
    "tipo": "Privada",
    "modalidad": "Híbrido",
    "duracion": "Anual",
    "precio": "Consultar",
    "moneda": "USD",
    "fecha": "2026-09-01",
    "url": "https://doaj.org/article/c80278c940ab41ffabbcc5a23d0179f6",
    "contacto": "info@slagf.org",
    "pais": "Multi-país Iberoamérica"
  },
  {
    "id": "FOR-038",
    "nombre": "Diplomado en Psicología Forense — IDEF Internacional 2026",
    "area": "Psicología Forense / Tribunal",
    "institucion": "IDEF Internacional (EE.UU./Chile)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Intensivo",
    "precio": "Consultar",
    "moneda": "USD",
    "fecha": "2026-06-01",
    "url": "https://idef.institute/curso_psicologia_forense/",
    "contacto": "info@idef.institute",
    "pais": "Multi-país Iberoamérica"
  },
  {
    "id": "FOR-039",
    "nombre": "XXI Congreso Nacional de Psicología Forense — APFRA",
    "area": "Psicología Forense / Congreso",
    "institucion": "Asoc. de Psicólogos Forenses de la Rep. Argentina (APFRA)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "2 Días",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-08-21",
    "url": "https://apfra.org/category/congresos/",
    "contacto": "info@apfra.org",
    "pais": "Argentina"
  },
  {
    "id": "FOR-040",
    "nombre": "Jornadas Internacionales de Accidentología Vial",
    "area": "Accidentología Vial / Reconstrucción",
    "institucion": "Formación Forense (Argentina)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Jornada Internacional",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-05-01",
    "url": "https://formacionforense.com.ar/cursos/jornada-accidentologia/",
    "contacto": "info@formacionforense.com.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-041",
    "nombre": "Diplomatura en Investigación Criminal — UTN",
    "area": "Documentología / Balística / Toxicología",
    "institucion": "Universidad Tecnológica Nacional (UTN-FRRQ)",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "Modular",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-03-01",
    "url": "https://aprenderonline.frrq.utn.edu.ar/curso/diplomatura-en-investigacion-criminal/",
    "contacto": "aprenderonline@frrq.utn.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-042",
    "nombre": "Tec. Univ. en Siniestrología y Accidentología Vial",
    "area": "Siniestrología / Accidentología Vial",
    "institucion": "Universidad del Aconcagua (UDA)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "Pregrado",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-03-09",
    "url": "https://www.uda.edu.ar/index.php/oferta-educativa-fpsi/carreras-de-grado/licenciatura-en-criminalistica",
    "contacto": "info@uda.edu.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-043",
    "nombre": "CIMELCIF — Congreso Internacional de Medicina Legal y Cs. Forenses",
    "area": "Entomotoxicología / Serología / Multidisciplinaria",
    "institucion": "Ministerio Público Fiscal de Córdoba",
    "tipo": "Pública",
    "modalidad": "Presencial",
    "duracion": "3 Días + Precongreso",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-04-28",
    "url": "https://cimelcif.com.ar/",
    "contacto": "info@cimelcif.com.ar",
    "pais": "Argentina"
  },
  {
    "id": "FOR-044",
    "nombre": "Pós-graduação em Ciências Forenses e Perícia Criminal",
    "area": "Ciencias Forenses / Pericia Criminal",
    "institucion": "Universidade Estácio de Sá",
    "tipo": "Privada",
    "modalidad": "Híbrido",
    "duracion": "Lato Sensu",
    "precio": "R$ 50-225 /mes",
    "moneda": "BRL",
    "fecha": "2026-03-01",
    "url": "https://estacio.br/cursos/pos-graduacao/ciencias-forenses-e-pericia-criminal",
    "contacto": "posgrado@estacio.br",
    "pais": "Brasil"
  },
  {
    "id": "FOR-045",
    "nombre": "Pós em Perícia Criminal e Ciências Forenses — UNIT",
    "area": "Pericia Ambiental / Balística / Incendios",
    "institucion": "Universidade Tiradentes (UNIT)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "Lato Sensu",
    "precio": "Consultar",
    "moneda": "BRL",
    "fecha": "2026-03-01",
    "url": "https://www.unit.br/pos/humanas/pericia-criminal-e-ciencias-forenses",
    "contacto": "posgrado@unit.br",
    "pais": "Brasil"
  },
  {
    "id": "FOR-046",
    "nombre": "Especialização em Perícia Forense — Unoeste",
    "area": "Pericia Forense / Laudos",
    "institucion": "Universidade do Oeste Paulista (Unoeste)",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "20 parcelas",
    "precio": "R$ 676,52 /mes",
    "moneda": "BRL",
    "fecha": "2026-05-14",
    "url": "https://www.unoeste.br/pos/pericia-forense",
    "contacto": "posgrado@unoeste.br",
    "pais": "Brasil"
  },
  {
    "id": "FOR-047",
    "nombre": "Diplomado en Ciencias Forenses 10° Versión — Unifranz",
    "area": "Documentología / Balística / Dactiloscopia",
    "institucion": "Universidad Privada Franz Tamayo (Unifranz)",
    "tipo": "Privada",
    "modalidad": "Híbrido",
    "duracion": "9 Módulos",
    "precio": "Consultar",
    "moneda": "BOB",
    "fecha": "2026-03-01",
    "url": "https://postgrado.unifranz.edu.bo/programa/diplomado-en-ciencias-forenses-10-version/",
    "contacto": "postgrado@unifranz.edu.bo",
    "pais": "Bolivia"
  },
  {
    "id": "FOR-048",
    "nombre": "Diplomado en Medicina Forense — TECH Uruguay",
    "area": "Medicina Forense / Actualización",
    "institucion": "TECH Universidad Tecnológica (Uruguay)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Diplomado",
    "precio": "Consultar",
    "moneda": "UYU",
    "fecha": "2026-01-01",
    "url": "https://www.techtitute.com/uy/medicina/diplomado/medicina-forense",
    "contacto": "info@techtitute.com",
    "pais": "Uruguay"
  },
  {
    "id": "FOR-049",
    "nombre": "Diplomado en Accidentología Vial — CEMP",
    "area": "Accidentología Vial / Peritaje",
    "institucion": "Centro de Estudios Médicos y Periciales (CEMP Quirón)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "4 Meses / 4 Mód.",
    "precio": "Consultar",
    "moneda": "PYG",
    "fecha": "2026-04-01",
    "url": "http://cempquiron.com/dipaccvia20211111",
    "contacto": "info@cempquiron.com",
    "pais": "Paraguay"
  },
  {
    "id": "FOR-051",
    "nombre": "I Jornada de Criminología y Política Criminal en la era de la IA",
    "area": "Criminología / IA / Política Criminal",
    "institucion": "Colegio de Criminólogos de Madrid",
    "tipo": "Privada",
    "modalidad": "Presencial",
    "duracion": "1 Día (gratuita)",
    "precio": "Gratuito",
    "moneda": "EUR",
    "fecha": "2026-03-03",
    "url": "https://colegiocriminologosmadrid.es/jornada-congreso-2026/",
    "contacto": "info@colegiocriminologosmadrid.es",
    "pais": "España"
  },
  {
    "id": "FOR-052",
    "nombre": "Congreso Online de Antropología Forense — Domingo entre Huesos",
    "area": "Antropología Forense / Arqueología",
    "institucion": "Instituto de Formación en Patología y Cs. Forenses (IFPCF)",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "Online intensivo",
    "precio": "Consultar",
    "moneda": "EUR",
    "fecha": "2026-06-01",
    "url": "https://www.institutoforense.net/congreso",
    "contacto": "info@institutoforense.net",
    "pais": "España"
  },
  {
    "id": "FOR-053",
    "nombre": "Perspectivas Actuales en el Relevamiento del Lugar del Hecho",
    "area": "Criminalística / Escena del Hecho",
    "institucion": "AMFRA — Asociación de Médicos Forenses de la República Argentina",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "1 Jornada (Zoom)",
    "precio": "15000",
    "moneda": "ARS",
    "fecha": "2026-07-01",
    "url": "mailto:amfraforenses@gmail.com",
    "contacto": "amfraforenses@gmail.com",
    "pais": "Argentina",
    "docente": "Dr. Héctor Di Salvo",
    "detalle": "Médico especialista en cirugía general, vascular y medicina legal. Doctor en medicina. Docente Autorizado UBA. Perito Médico Forense — Morgue Judicial Corte Suprema. Derecho a certificado. No socios: $15.000 ARS. Zoom Libre · 1 de Julio 20 h."
  },
  {
    "id": "FOR-054",
    "nombre": "VI Congreso Internacional sobre Psicología Jurídica y Derecho Penal: Desaparición de Personas desde una Visión Social y Forense",
    "area": "Psicología Jurídica / Derecho Penal / Forense",
    "institucion": "IPSIJUS + AMPJyOF",
    "tipo": "Pública",
    "modalidad": "Virtual",
    "duracion": "2 Días",
    "precio": "Gratuito",
    "moneda": "ARS",
    "fecha": "2026-09-25",
    "url": "",
    "contacto": "Zoom · Unete al grupo del Congreso",
    "pais": "México / Argentina",
    "docente": "Dra. María Sol Berenice Salgado Ambros (Conferencia de Apertura)",
    "detalle": "Conferencia de apertura: 'El Contexto de la Desaparición en México'. Expositora: Dra. María Sol Berenice Salgado Ambros — Lic. y Dra. en Derecho (UAEM). Directora General de Coordinación para la Atención Integral a la Migración en Frontera Sur (Sec. Gobernación). Doctorante en Derecho Penal y Ciencias Forenses. Certificada Programa Alerta AMBER México. Actividad gratuita — 25 y 26 de septiembre 2026."
  },
  {
    "id": "FOR-055",
    "nombre": "Cursos de Capacitación en Práctica Procesal para Peritos y Martilleros",
    "area": "Práctica Pericial / Derecho Procesal",
    "institucion": "Capacitación Procesal — Peritos y Martilleros",
    "tipo": "Privada",
    "modalidad": "Virtual",
    "duracion": "A confirmar",
    "precio": "Consultar",
    "moneda": "ARS",
    "fecha": "2026-07-01",
    "url": "",
    "contacto": "Consultar programa adjunto",
    "pais": "Argentina",
    "detalle": "Programa de formación en práctica procesal orientado a peritos y martilleros judiciales. Consultar presentación completa del programa para aranceles y modalidad de cursada."
  }
];
window.MCF_CAPACITACIONES = MCF_CAPACITACIONES;
